# Generated by Django 5.0.6 on 2024-05-20 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_photo_userconfirmation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='AUTH_STATUS',
            new_name='auth_status',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='AUTH_TYPE',
            new_name='auth_type',
        ),
    ]
